version: "3.7"

services:
  web:
    image: docker.pkg.github.com/arwynfr/homepage/homepage:master
    networks:
      - reverse
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
      - source: expires
        target: /etc/nginx/conf.d/expires.global
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.homepage.loadBalancer.server.port=80"
        - "traefik.http.middlewares.homepage.headers.sslHost=www.arwyn.fr"
        - "traefik.http.middlewares.homepage.headers.sslRedirect=true"
        - "traefik.http.middlewares.homepage.headers.sslForceHost=true"
        - "traefik.http.middlewares.homepage.headers.stsSeconds=31536000"
        - "traefik.http.middlewares.homepage.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.homepage.headers.forceStsHeader=true"
        - "traefik.http.routers.homepage.entrypoints=https"
        - "traefik.http.routers.homepage.rule=Host(`arwyn.fr`,`www.arwyn.fr`)"
        - "traefik.http.routers.homepage.middlewares=homepage@docker"
        - "traefik.http.routers.homepage.service=homepage"
        - "traefik.http.routers.homepage.tls.options=secure@file"
        - "traefik.http.routers.homepage.tls.certResolver=gandi"
        - "traefik.http.routers.homepage_unsecure.entrypoints=http"
        - "traefik.http.routers.homepage_unsecure.rule=Host(`arwyn.fr`,`www.arwyn.fr`)"
        - "traefik.http.routers.homepage_unsecure.middlewares=homepage@docker"
        - "traefik.http.routers.homepage_unsecure.service=homepage"
    logging:
      driver: gelf
      options:
        gelf-address: udp://seq.chezsquall.net:11201

networks:
  reverse:
    external: true

configs:
  nginx:
    file: ./nginx.conf
  expires:
    file: ./expires.conf
