apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: www.arwyn.fr
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header Cache-Control "public, max-age=86400";
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
      gzip on;
      gzip_buffers 16 8k;
      gzip_comp_level 6;
      gzip_disable "msie6";
      gzip_http_version 1.1;
      gzip_min_length 256;
      gzip_proxied any;
      gzip_types text/css text/html application/javascript;
      gzip_vary on;
spec:
  tls:
    - secretName: cert-www-arwyn-fr
      hosts:
        - www.arwyn.fr
        - arwyn.fr
  rules:
    - host: www.arwyn.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 8080
