name: continuous-deployment

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v2
        
      - name: Login with registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/arwynfr/homepage:master
          docker build ./src --tag $IMAGE
          docker push $IMAGE

  deploy:
    needs: build
    runs-on: self-hosted
    steps:

      - name: Checkout stack files
        uses: actions/checkout@v2

      - name: Deploy stack to the swarm
        run: |
          docker pull ghcr.io/arwynfr/homepage:master
          docker stack deploy --compose-file stack/docker-compose.yml --prune homepage
          docker service update --force homepage_web
