name: continuous-deployment

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: arwynfr/stack-homepage/homepage
          username: ${{ github.actor }}
          password: ${{ github.token }}
          tags: master
          path: ./src

  deploy:
    needs: build
    runs-on: self-hosted
    steps:

      - name: Checkout stack files
        uses: actions/checkout@v2
        with:
          repository: arwynfr/homepage-stack

      - name: Deploy stack to the swarm
        run: docker pull docker.pkg.github.com/arwynfr/stack-homepage/homepage:master && docker stack deploy --compose-file docker-compose.yml --prune homepage
