name: deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

env:
  OCI_REGISTRY: ghcr.io
  PACKAGE_DOCKER: homepage-docker
  PACKAGE_HELM: homepage-helm
  PATH_DOCKER_CONTEXT: ./src
  PATH_HELM_CHART: ./build/helm

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 🔓 Docker login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ${{ env.OCI_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: 🔨 Git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 🔨 Version number
        run: ./build/version/New-ReleaseVersion.ps1
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: 🔨 install dotnet tools
        run: dotnet tool restore

      - name: 🔨 restore libman libs
        run: dotnet tool run libman restore

      - name: 📦 Build Docker image
        run: docker build ${PATH_DOCKER_CONTEXT} --tag "${OCI_REGISTRY}/${GITHUB_REPOSITORY@L}/${PACKAGE_DOCKER}:${VERSION}"

      - name: 📦 Package Helm chart
        run: helm package ${PATH_HELM_CHART} --version "${VERSION}"

      - name: 📌 Push Docker image
        run: docker push "${OCI_REGISTRY}/${GITHUB_REPOSITORY@L}/${PACKAGE_DOCKER}:${VERSION}"

      - name: 📌 Push Helm chart
        run: helm push "${PACKAGE_HELM}-${VERSION}.tgz" "oci://${OCI_REGISTRY}/${GITHUB_REPOSITORY@L}"

      - name: 📣 Create GH release
        run: gh release create "${VERSION}" --generate-notes --target "${GITHUB_SHA}"
        env:
          GH_TOKEN: ${{ github.token }}
