name: deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  OCI_REGISTRY: ghcr.io
  PACKAGE_DOCKER: homepage-docker
  PACKAGE_HELM: homepage-helm
  PATH_DOCKER_CONTEXT: ./src
  PATH_HELM_CHART: ./build/helm

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 🔓 Docker login
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ${{ env.OCI_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: 🔨 Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: 🔨 Version number
        run: ./build/version/New-ReleaseVersion.ps1
        shell: pwsh
        id: version
        env:
          GH_TOKEN: ${{ github.token }}

      - name: 🔨 install dotnet tools
        run: dotnet tool restore

      - name: 🔨 restore libman libs
        run: dotnet tool run libman restore

      - name: 📦 Build Docker image
        run: docker build ${PATH_DOCKER_CONTEXT} --tag ${OCI_REGISTRY}/${GITHUB_REPOSITORY@L}/${PACKAGE_DOCKER}:${{ steps.version.outputs.version }}

      - name: 📦 Package Helm chart
        run: helm package ${PATH_HELM_CHART} --version ${{ steps.version.outputs.version }}

      - name: 📌 Push Docker image
        run: docker push ${OCI_REGISTRY}/${GITHUB_REPOSITORY@L}/${PACKAGE_DOCKER}:${{ steps.version.outputs.version }}

      - name: 📌 Push Helm chart
        run: helm push ${PACKAGE_HELM}-${{ steps.version.outputs.version }}.tgz oci://${OCI_REGISTRY}/${GITHUB_REPOSITORY@L}

      - name: 📣 Create GH release
        run: gh release create ${{ steps.version.outputs.version }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
